### ISSUE TITLE
Getting 401 error from the API gateway

### ISSUE THREAD

**Issue by bbarthel** [aws-samples/ask-around-me#3]
![image](https://user-images.githubusercontent.com/4349780/84822128-d38da800-afe1-11ea-94a1-11396401af03.png)

**Comment by jbesw** [comment]
In the [backend template](https://github.com/aws-samples/ask-around-me/blob/master/backend/template.yaml), the audience is defaulted to "https://auth0-jwt-authorizer". If this is different, you can change this in the API Gateway console under Authorizers. The audience MUST match what's in the token precisely (ie. if you have more than one audience, then you must have all listed).

If you console.log the token (uncomment line 170 in https://github.com/aws-samples/ask-around-me/blob/master/frontend/src/views/HomeView.vue), and then decode the token in https://jwt.io/, it will show the audiences in the token. Once API Gateway's Authorizer matches, this error will go away.

**Comment by bbarthel** [comment]
Decoded:
"aud": [
    "https://auth0-jwt-authorizer",
    "https://dev--vm0t8mn.auth0.com/userinfo"
  ],

So, I added the audience https://dev--vm0t8mn.auth0.com/userinfo to the API gateway
![image](https://user-images.githubusercontent.com/4349780/84824812-1ea9ba00-afe6-11ea-8a5b-de1be446a707.png)

Still getting the 401 error

**Comment by bbarthel** [comment]
I figured it out, the Issuer needs to have a trailing '/' in the API Gateway

**Comment by jbesw** [comment]
Great to hear you solved it - I'll update the instructions to highlight this. I'm recording a video soon too, so I'll mention this to make it easier for people. Thanks for sharing!
